[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = [ "g", "r" ]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "cd to root of current git repository"

[[mgr.prepend_keymap]]
on = [ "g", "d" ]
run = 'cd ~/downloads'
desc = "Go ~/downloads"

[[mgr.prepend_keymap]]
on = [ "g", "D" ]
run = 'cd ~/documents'
desc = "Go ~/documents"

[[mgr.prepend_keymap]]
on = [ "g", "p" ]
run = 'cd ~/projects'
desc = "Go ~/projects"

[[mgr.prepend_keymap]]
on = [ "g", "u" ]
run = 'cd ~/documents/uni'
desc = "Go ~/documents/uni"
