general.import = [ "themes/themes/gruvbox_dark.toml" ]

font.normal.family = "FiraCode Nerd Font Mono"
font.size = 12

window.padding.x = 3
window.padding.y = 3
window.dynamic_padding = true
window.opacity = 0.9

env.TERM = "xterm-256color"
