# {# replace_re("light|dark", theme_name) #}
general.import = ["themes/themes/gruvbox_dark.toml"]

font.normal.family = "FiraCode Nerd Font Mono"
font.size = 10.5

window.dynamic_padding = true

env.TERM = "xterm-256color"
